name: 'IIS Webdeploy powershell'
description: 'An action for deploying web applications to IIS server using Windows powershell'
author: 'Siavash Namvar'
inputs:
  source:  
    description: 'source zip file, or app_offline.htm'
    required: true
  destination:  
    description: 'destination path on IIS server'
    required: true
  remote_url:  
    description: 'IIS URL'
    required: true  
  username:  
    description: 'IIS/Windows username'
    required: false
    default: ""
  password:  
    description: 'IIS/Windows password'
    required: false
    default: ""
  type:
    description: 'type of IIS deployment, add_appoffline, del_appoffline, full, add_single_file, del_single_file'
    required: false
    default: ""
  msdeploy_path:
    description: 'path to msdeploy.exe'
    required: false
    default: 'C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe'
    

runs:
  using: "composite"
  steps:
    - run: |       
        echo "project app"     

        $src = '${{ inputs.source }}'
        $dest = '${{ inputs.destination }}'
        $cname = '${{ inputs.remote_url }}'
        $username = '${{ inputs.username }}'
        $password = '${{ inputs.password }}'
        $auth = 'Basic'
        $msdeploy = Get-Command '${{ inputs.msdeploy_path }}'
        $command = "& `$msdeploy --% -verb:sync -AllowUntrusted -source:package=""$src"" -dest:contentPath=""$dest"",computerName=""$cname"",IncludeAcls=False,username=""$username"",password=""$password"",authType=""$auth"""
        $sb = $ExecutionContext.InvokeCommand.NewScriptBlock($command)
        & $sb
      shell: powershell
      if: ${{ inputs.type == 'full' }}

    - run: |       
        echo "Make website offline"     

        $src = '${{ inputs.source }}'
        $dest = '${{ inputs.destination }}'
        $cname = '${{ inputs.remote_url }}'
        $username = '${{ inputs.username }}'
        $password = '${{ inputs.password }}'
        $auth = 'Basic'
        $currentDir = "${{ github.workspace }}"

        $msdeploy = Get-Command '${{ inputs.msdeploy_path }}'
        $command = "& `$msdeploy --% -verb:sync -AllowUntrusted -source:contentPath=""$currentDir\$src"" -dest:contentPath=""$dest\App_offline.htm"",computerName=""$cname"",IncludeAcls=False,username=""$username"",password=""$password"",authType=""$auth"""
        $sb = $ExecutionContext.InvokeCommand.NewScriptBlock($command)
        & $sb
      shell: powershell
      if: ${{ inputs.type == 'add_appoffline' }}

    - run: |       
        echo "project app"     

        $src = '${{ inputs.source }}'
        $dest = '${{ inputs.destination }}'
        $cname = '${{ inputs.remote_url }}'
        $username = '${{ inputs.username }}'
        $password = '${{ inputs.password }}'
        $auth = 'Basic'
        $msdeploy = Get-Command '${{ inputs.msdeploy_path }}'
        $command = "& `$msdeploy --% -verb:delete -AllowUntrusted -dest:contentPath=""$dest\App_offline.htm"",computerName=""$cname"",IncludeAcls=False,username=""$username"",password=""$password"",authType=""$auth"""
        $sb = $ExecutionContext.InvokeCommand.NewScriptBlock($command)
        & $sb
      shell: powershell
      if: ${{ inputs.type == 'del_appoffline' }}


    - run: |       
        echo "Add a single file"     

        $src = '${{ inputs.source }}'
        $dest = '${{ inputs.destination }}'
        $cname = '${{ inputs.remote_url }}'
        $username = '${{ inputs.username }}'
        $password = '${{ inputs.password }}'
        $auth = 'Basic'
        $currentDir = "${{ github.workspace }}"

        $zipPath = "$src"
        $extractPath = "$currentDir\extracted"
        Expand-Archive -Path $zipPath -DestinationPath $extractPath -Force

        # Assuming the single file is the only file in the zip
        $filePath = Get-ChildItem -Path $extractPath -File | Select-Object -First 1
        $fileName = $filePath.Name

        $msdeploy = Get-Command '${{ inputs.msdeploy_path }}'
        # msdeploy.exe -verb:sync -source:contentPath='path\to\test.csproj' -dest:contentPath='IIS Web Application Name\test.csproj',computerName='http://localhost:8172/msdeploy.axd',userName='your-username',password='your-password',authType='Basic',includeAcls='False' -enableRule:DoNotDeleteRule
        $command = "& `$msdeploy --% -verb:sync -AllowUntrusted -source:contentPath=""$currentDir\$src"" -dest:contentPath=""$dest"",computerName=""$cname"",IncludeAcls=False,username=""$username"",password=""$password"",authType=""$auth"" -enableRule:DoNotDeleteRule"
                # msdeploy -verb:sync -source:package="path\to\your\package.zip" -dest:iisApp="domain.com/appfolder" ,wmsvc=domain.com,username=IIS_username,password=IIS_password -allowUntrusted=true
                # $command = "& `$msdeploy --% -verb:sync -AllowUntrusted -source:contentPath=""$filePath"" -dest:contentPath=""$dest\$($filePath.Name)"",computerName=""$cname"",IncludeAcls=False,username=""$username"",password=""$password"",authType=""$auth"""

        # $msdeploy = Get-Command '${{ inputs.msdeploy_path }}'
        # $command = "& `$msdeploy --% -verb:sync -AllowUntrusted -source:contentPath=""$currentDir\$src"" -dest:contentPath=""$dest\$src"",computerName=""$cname"",IncludeAcls=False,username=""$username"",password=""$password"",authType=""$auth"""
        $sb = $ExecutionContext.InvokeCommand.NewScriptBlock($command)
        & $sb
      shell: powershell
      if: ${{ inputs.type == 'add_single_file' }}

    - run: |       
        echo "Delete a single file"     

        $src = '${{ inputs.source }}'
        $dest = '${{ inputs.destination }}'
        $cname = '${{ inputs.remote_url }}'
        $username = '${{ inputs.username }}'
        $password = '${{ inputs.password }}'
        $auth = 'Basic'
        $msdeploy = Get-Command '${{ inputs.msdeploy_path }}'
        $command = "& `$msdeploy --% -verb:delete -AllowUntrusted -dest:contentPath=""$dest\$src"",computerName=""$cname"",IncludeAcls=False,username=""$username"",password=""$password"",authType=""$auth"""
        $sb = $ExecutionContext.InvokeCommand.NewScriptBlock($command)
        & $sb
      shell: powershell
      if: ${{ inputs.type == 'del_single_file' }}
