name: 'IIS Webdeploy powershell'
description: 'An action for deploying web applications to IIS server using Windows powershell'
author: 'Siavash Namvar'
inputs:
  source:  
    description: 'source zip file, or app_offline.htm'
    required: true
  destination:  
    description: 'destination path on IIS server'
    required: true
  remote_url:  
    description: 'IIS URL'
    required: true  
  username:  
    description: 'IIS/Windows username'
    required: false
    default: ""
  password:  
    description: 'IIS/Windows password'
    required: false
    default: ""
  type:
    description: 'type of IIS deployment, add_appoffline, del_appoffline, full'
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - run: |       
        echo "project app"     

        $src = '${{ inputs.source }}'
        $dest = '${{ inputs.destination }}'
        $cname = '${{ inputs.remote_url }}'
        $username = '${{ inputs.username }}'
        $password = '${{ inputs.password }}'
        $auth = 'Basic'
        $msdeploy = Get-Command 'C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe'
        $command = "& `$msdeploy --% -verb:sync -AllowUntrusted -source:package=""$src"" -dest:contentPath=""$dest"",computerName=""$cname"",IncludeAcls=False,username=""$username"",password=""$password"",authType=""$auth"""
        $sb = $ExecutionContext.InvokeCommand.NewScriptBlock($command)
        & $sb
      shell: powershell
      if: ${{ inputs.type == 'full' }}

    - run: |       
        echo "Make website offline"     

        $src = '${{ inputs.source }}'
        $dest = '${{ inputs.destination }}'
        $cname = '${{ inputs.remote_url }}'
        $username = '${{ inputs.username }}'
        $password = '${{ inputs.password }}'
        $auth = 'Basic'
        echo "$dest\$src" $src $cname 
        $msdeploy = Get-Command 'C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe'
        $command = "& `$msdeploy --% -verb:sync -AllowUntrusted -source:contentPath=""$src"" -dest:contentPath=""$dest\App_offline.htm"",computerName=""$cname"",IncludeAcls=False,username=""$username"",password=""$password"",authType=""$auth"""
        $sb = $ExecutionContext.InvokeCommand.NewScriptBlock($command)
        & $sb
      shell: powershell
      if: ${{ inputs.type == 'add_appoffline' }}

    - run: |       
        echo "project app"     

        $src = '${{ inputs.source }}'
        $dest = '${{ inputs.destination }}'
        $cname = '${{ inputs.remote_url }}'
        $username = '${{ inputs.username }}'
        $password = '${{ inputs.password }}'
        $auth = 'Basic'
        $msdeploy = Get-Command 'C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe'
        $command = "& `$msdeploy --% -verb:delete -AllowUntrusted -dest:contentPath=""$dest\App_offline.htm"",computerName=""$cname"",IncludeAcls=False,username=""$username"",password=""$password"",authType=""$auth"""
        $sb = $ExecutionContext.InvokeCommand.NewScriptBlock($command)
        & $sb
      shell: powershell
      if: ${{ inputs.type == 'del_appoffline' }}
